### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by AndrewTack** [christianascone/expo-stripe-checkout-sca#3]
Hey Christian!

Your library was extremely helpful for me in implementing the newest version of Stripe Checkout (https://stripe.com/docs/payments/checkout/one-time). I wasn't sure how else to reach you other than by posting here. Thank you!

Best,
Andrew

**Comment by AndrewTack** [comment]
Still not fully understanding log(e) and onClose() functionality. If you see this and can provide any insight that'd be appreciated!

**Comment by christianascone** [comment]
Hi @AndrewTack .
I'm glad to hear this project was helpful for you. Sorry for the delay, I created this repository without knowing it would have been helpful for other people.

Currently I found out the Stripe javascript changed so there is no a success callback, that's why I suggest to use the `log` function (I will explain this better in readme too).
Every time the WebView changes url, it calls the `onNavigationStateChange` function, so you are able to check if new one is the success/error callback url you passed as parameter during the Stripe session creation (I check this in log function).

The `onClose` is just a function which is called when you click the X button (top-left corner). You could just change the state in order to hide your modal.

This is an example of a real implementation in my project:
```typescript
/**
* Logs when webview url changes
* @param e
*/
log(e) {
    let url: string = e.url;
    if (url == 'http://success.com'){
        this.setState({modalVisible: false}); // <-- This will hide my modal due to payment success
    }
}

render() {
  return <StripeCheckoutSca modalVisible={this.state.modalVisible}
    onClose={this.setState({modalVisible: false})}
    onNavigationStateChange={(e) => this.log(e)}
    publicKey="pk_test_jr2LmM4cWdn3Q5vuFqgo5LMO"
    sessionId="cs_test_9pGYF9ZP3OBcOHVlKjDM0Bjw0k0wsqSQLxsagv3L05VImpbV1iZAzcG1"
  />
}
```

Hope this sounds clear to you. Let me know if you need further details.

**Comment by AndrewTack** [comment]
Hi @christianascone 

I ended up figuring out the `log` function on my own, for me I'm using a more specific IF statement, I'll share in case it helps someone else...

if (url === `http://${IP}:3000/success.html?session_id=${this.props.stripeSessionObject.id}`) {
}

For some reason I had still been struggling with the X button though when using this code for ios not Andriod. By moving the button down lower by increasing the marginTop in the closeButtonOpacity styles I was able to get this working. Thank you again!!

Best,
Andrew

**Comment by christianascone** [comment]
I'm happy to hear you solved the problem.
I'm gonna update project documentation in order to make these features clearer.

Thank you for your interest
